### ISSUE TITLE
Specify a polygon geometry with a Shape file 

### ISSUE THREAD

**Issue by korvinos** [nansencenter/django-geo-spaas-sar-doppler#23]
## Description

A feature introduced in #6 and then improved in #12 allows specifying a domain for data ingesting, processing, etc. Methodology, implemented at the moment allows specifying borders and Spatial reference for the domain. It is a very sustainable approach since satisfying a methodology of creating domains implemented in both `gdal` and `nansat`.

However, in some cases, it would be beneficial to introduce a nor rectangular domain with a specific shape (i.e. a shape of land objects). 

Thus, it should be implemented in the injestor. 

## Solution

Since it is not very convenient to hardcode a shape in command line while ingesting it can be provided in `.shp` file or another format such as `GeoJSON`. It is important, that:

1. The new feature should complement the more primitive but simple and stable method implemented earlier but not cancel it.
2. The shape will have a higher priority than a "domain"  (i.e. if both were provided, the shape would be used)
 
## TODO

- [x] Find a suitable for the case file format (Shape, GeoJSON, etc.)
- [ ] Update a `BaseCommand` as it can take a path to the file and handle reading/validation of the output
- [ ] Update Manager
- [ ] Update tests

**Comment by mortenwh** [comment]
Wouldn't this be good to have in Django-Geo-SpaaS? Seems like a general
feature that could be useful in other settings a well. We could move it
later, though...

Den søn. 29. jul. 2018, 11:32 skrev Artem Moiseev <notifications@github.com

**Comment by korvinos** [comment]
Adding it to the geo-spaas is indeed a good idea was also mentioned at the meeting we had about a month ago. But along with that, creating of a generic method should be carefully designed to be used for all (or major) part of applications. Thus in view of the upcoming sprint, you can move it to the geo-spaas later with probably some changes.

**Comment by korvinos** [comment]
Maybe @akorosov could also comment on this?

**Comment by korvinos** [comment]
I have done a quick research around and found that GeoJSON could be the best option for providing a domain/geometry specification.

#### Advantages:

- Well documented (last revision of the standard is from 2016, RFC7946: https://tools.ietf.org/html/rfc7946
- Since it is, basically, a text file, consequently, it makes it easier for modification and usage in daily work. Nice tool for generating GeoJSON online: http://geojson.io/#map=2/20.0/0.0
- Nansat (v1.1) provides functionality for exporting a domain to json.

#### Disadvantages:

- Does not allow specifying of a Spatial reference system after last revision of the standard (RFC7946, page 25, Appendix B.1)

**Comment by korvinos** [comment]
Solved in https://github.com/nansencenter/django-geo-spaas/pull/29
